### ISSUE TITLE
Configuration issues?

### ISSUE THREAD

**Issue by GutHib** [moisseev/rspamd-spamness#12]
Hi,

Very happy to find an alternative to Spamness since it seems that is no longer maintained.

I'm having troubles with the configuration, though. Advanced settings allow to specify the mail header, but that doesn't seem to do the trick for me. My headers look like this:

X-Spam-Status: No, score=1.7

If "X-Spam-Status" isn't the correct header, what is?

Thanks!

**Comment by moisseev** [comment]
Hi,
It looks like SpamAssasin's header. Rspamd-spamness is for [Rspamd](https://rspamd.com/).

**Comment by GutHib** [comment]
Ah, that's too bad. And sad.
