### ISSUE TITLE
[Enhancement] Up-Down sorting arrows

### ISSUE THREAD

**Issue by dehnli** [moisseev/rspamd-spamness#14]
Is it possible to add up-down arrows when sorting by Rspamd spam score as it made for Theme column for example?

![rspamd-spamness-up-down-arrow-sorting](https://user-images.githubusercontent.com/14199981/51562101-02115d00-1e9a-11e9-9936-03059acfaa77.png)

**Comment by moisseev** [comment]
This is fixed in the upcoming release: https://github.com/moisseev/rspamd-spamness/commit/b6d96357bd3fba457a6cca6c152204b0cbaec9e3
