### ISSUE TITLE
Config wrrong?

### ISSUE THREAD

**Issue by DjCrays** [moisseev/rspamd-spamness#15]
Hey,

i have the Problem that if i change the Advanced Options in Rspamd-spamness Optionsmenu to the Email Header given by my hoster (Uberspace.de) it wont work. Even after restart, new install of the Addon nothing works. Here are some examples of the Header i get from Uberspace.de. 

`Received: (qmail 28480 invoked by uid 498); 6 Mar 2019 19:16:24 -0000
Received: from mta1a10.sp.crdl.io (mta1a10.sp.crdl.io [52.43.108.229])
	by brorsen.uberspace.de (Haraka/2.8.18) with ESMTPS id DBC9A921-EE8C-47DC-8762-6549D393D996.1
	envelope-from <XXXXXXXX@mailer.humblebundle.com>
	(version=TLSv1/SSLv3 cipher=DHE-RSA-AES256-GCM-SHA384 verify=FAIL);
	Wed, 06 Mar 2019 20:16:17 +0100
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
	d=mailer.humblebundle.com; s=scph0816; t=1551899769;
	i=@mailer.humblebundle.com;
	bh=i2PQJT0Hec6l1tW+HfAMT8Ox9yUKdf2FvD2XqOf159I=;
	h=Content-Type:To:Message-ID:Date:Subject:From;
	b=dB0abrmhdRqc7Ip0DYnR5P4vspNUClUtgA4/0exSUrtSywgwud2QGFQUDGOK0Vkgb
	 v3vj5JN/wCVg4eRJpb2mA4wbRCDltzrYZARB5O06UsidtbuX1BxlnGudZHTuPEcS1L
	 avSg2a8wozbVmHkukwZj4cl9D+3bM3Y6CM5aOriE=
X-MSFBL: Ql3ElGPu6nKA2JVKuvpPSp4bZNL41rn6YjYKtKpjt+s=|eyJzdWJhY2NvdW50X2l
	kIjoiMTMiLCJtZXNzYWdlX2lkIjoiMDAyNDc5MWM4MDVjMGY4N2Y4YzMiLCJyIjo
	iaGFsbG9AZC1rdS5kZSIsInRlbmFudF9pZCI6ImNvcmRpYWwiLCJjdXN0b21lcl9
	pZCI6IjEifQ==
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset="UTF-8"
To: XXXXXXXXX@d-ku.de
Message-ID: <8F.3C.34575.97C108C5@aj.mta2vrest.cc.prd.sparkpost>
Date: Wed, 06 Mar 2019 19:16:09 +0000
MIME-Version: 1.0
Reply-To: contact@humblebundle.com
Subject: Travel to the 31st millennium with the Humble Book Bundle: The Horus Heresy 2019 by Black Library!
X-Crdl-Mc: 102:5c786891382c295e74d41eb1:ot:5a397c32c438005fac400d41:1
From: "Humble Bundle" <contact@mailer.humblebundle.com>
List-Unsubscribe: <mailto:unsubscribe@sp.crdl.io?subject=unsubscribe:Ft1gk-dbBclMzglwdG3IBV1tnwp0Ietb557Xnl9uy-I~|eyAicmNwdF90byI6ICJoYWxsb0BkLWt1LmRlIiwgInRlbmFudF9pZCI6ICJjb3JkaWFsIiwgImN1c3RvbWVyX2lkIjogIjEiLCAic3ViYWNjb3VudF9pZCI6ICIxMyIsICJtZXNzYWdlX2lkIjogIjAwMjQ3OTFjODA1YzBmODdmOGMzIiB9>
List-Id: <cordial-1-13>
X-Rspamd-Bar: +
X-Rspamd-Report: R_DKIM_ALLOW(-0.2) R_SPF_ALLOW(-0.2) HTML_SHORT_LINK_IMG_1(2) HAS_LIST_UNSUB(-0.01) MANY_INVISIBLE_PARTS(0.05) DMARC_POLICY_ALLOW(-0.5) MIME_HTML_ONLY(0.2) FORGED_SENDER(0.3) ONCE_RECEIVED(0.1)
X-Rspamd-Score: 1.74`

Also i observed that if i put in the Headers with an X insted of an x it gets auto set to all lowercase.

Could you look into it please and tell me what i did wrrong or what i sould say to my Hoster uberspace.de to get right in the Configs? Thanks. :)

**Comment by DjCrays** [comment]
Thunderbird Version: 60.5.3 (32-bit)
OS: Windows 10 
Rspamd-spamness Version: 0.8.8

**Comment by DjCrays** [comment]
Could you please build for me an XPI? Ive updated to 0.9 with the XPI here in the Rep. but since i fail to build it, could you do this please? :)

**Comment by moisseev** [comment]
Here you go: [add-on.zip](https://github.com/moisseev/rspamd-spamness/files/2949229/add-on.zip)
I can't attach `.xpi` files here. You can rename the add-on.zip to `.xpi` or just drag and drop it as is to `Add-ons Manager` tab.

Also I've added [instructions](https://github.com/moisseev/rspamd-spamness#creating-xpi-installer) how to create XPI from sources.

**Comment by DjCrays** [comment]
Yep, now it seams to Work. But why is in TB still the 0.8.X Version uptodate and not the 0.9 version? o.O

Is there maybe something going bonkers over at mozilla? :D 

But thank you :)

**Comment by moisseev** [comment]
Something like that, Thunderbird is moving to WebExtension API.
0.9 stuck in waiting for approval.

**Comment by DjCrays** [comment]
Well... i think ive got an new issue.. On Linux Ubuntu 18.04 LTS in Thunderbird i get the Rspamd-Score in Visual and in Header shown. On my Windows 10 Thunderbird i get no Header "Score" just "NaN (Bayes:undefined Fuzzy: undefined)". Its happend after i repaird my Mailboxes in Thunderbird. Do you need something more of my Errorlog or something else?

Greets,

Erwin.

**Comment by DjCrays** [comment]
okay.. now it gets strange.. I just redid all of my Thunderbird from Scratch.. Now anything gets shown again... So i think its just a "hickup" or something...
