### ISSUE TITLE
HAM/SPAM upload URIs

### ISSUE THREAD

**Issue by bonanza123** [moisseev/rspamd-spamness#16]
I have troubles with using the SPAM/HAM training.
I have have configured the URIs as follows:

```
mail.domain.org/rspamd/learnham
mail.domain.org/rspamd/learnspam
```

But this gives

> NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIMsgDBView.doCommandWithFolder]  mailWindowOverlay.js:1607
> 	MsgMoveMessage chrome://messenger/content/mailWindowOverlay.js:1607:3
> 	RspamdSpamness.moveMessage chrome://rspamd-spamness/content/scripts/spamness.js:237:9
> 	oncommand chrome://messenger/content/messenger.xul:1:1

What is the right way of setting the URIs? How to deal with rspmand authentication (wouldn't rspam ask for username/password before accepting some uploads?)

**Comment by moisseev** [comment]
The training buttons do not upload messages to Rspamd, it is just a convenient way to move or copy messages between folders in Thunderbird<sup>[1](#fn1)</sup>.

The URIs are not HTTP URIs, but Thunderbird folder URIs. Like `imap://spam%40example.com@imap.example.com/train_ham`. You can find URI of a folder at `General Information tab` of the `Folder Properties`.

<a name="fn1">1</a>: https://github.com/moisseev/rspamd-spamness#training-rspamd

**Comment by bonanza123** [comment]
Thanks for the clarification!
