### ISSUE TITLE
Make the extension work with Thunderbird 68.x

### ISSUE THREAD

**Issue by robinsmidsrod** [moisseev/rspamd-spamness#17]
After an upgrade to Thunderbird 68.x (installed via Ninite) I notice that this extension is no longer compatible. Thunderbird points me to this page: https://support.mozilla.org/en-US/kb/unable-install-add-on-extension-theme-thunderbird

I'm running Thunderbird 68.0 (32-bit) on Windows 10 Pro 64-bit 1903.

Is it possible to make the extension compatible with the new version?

**Comment by moisseev** [comment]
Mozilla completely removed traditional add-on support and transitioned to WebExtensions. The Thunderbird developers tried to keep some support for "legacy" extensions in TB 68, but a lot of code needed to run overlay add-ons had nevertheless been removed.

At this time there is not much documentation about updating for TB 68 or writing WebExtensions add-ons for Thunderbird. So I cannot say if it possible to rework the extension to make it compatible with TB 68 or it needs to be rewritten from scratch.

Moreover [the Thunderbird developers cannot say what will happen to add-ons in future TB releases](https://developer.thunderbird.net/add-ons/updates#the-future). Which makes rewriting the add-on a waste of time at the moment.

For now I would recommend to stay on Thunderbird `24.0` - `60.*`.

**Comment by pr3d** [comment]
Seems like it is (at least for now) enough to add a `manifest.json` and delete the `install.rdf `to install the add-on. I haven't discovered any bugs yet.

```json
{
	"applications": {
		"gecko": {
			"id": "rspamd-spamness@alexander.moisseev",
			"strict_min_version": "24.0",
			"strict_max_version": "70.*"
		}
	},
	"manifest_version": 2,
	"name": "Rspamd-spamness",
	"version": "0.9.2",
	"author": "Alexander Moisseev (moiseev@mezonplus.ru)",
	"homepage_url": "https://github.com/moisseev/rspamd-spamness",
	"description": "Provides a color- and size-based visual measurement of how spam-like an individual message is based on its normalized Rspamd score.",
	"legacy": {
		"type": "xul",
		"options": {
			"page": "chrome://Rspamd-spamness/content/options.xul",
			"open_in_tab": true
		}
	}
}
```

![scrn-folder](https://user-images.githubusercontent.com/9925957/66068161-60283100-e54d-11e9-8288-ad71e3bd94c2.png)
![scrn-version](https://user-images.githubusercontent.com/9925957/66068162-60283100-e54d-11e9-91a5-26cce457ea05.png)

**Comment by moisseev** [comment]
@pr3d 

> I haven't discovered any bugs yet.

... and the only thing it can do is to display the total spam score in the column. Everything else is broken.
If you really want to help, please show how to display Rspamd symbols in the message header pane. The add-on is almost useless without it.

**Comment by nyarlatothep** [comment]
> ... and the only thing it can do is to display the total spam score in the column. 
It may look like a small thing, but for me it's quite useful. Thanks for the tip.

Sure i would be glad if this plugin would be fully functional, but i'm happy with what i get. Keep up!

**Comment by ITwrx** [comment]
> For now I would recommend to stay on Thunderbird 24.0 - 60.*

from my perspective that's not a viable option for security reasons. 
Maybe tbird can just replace built-in support for dspam, bogofilter, etc with rspamd.

**Comment by RemcodM** [comment]
Hi. I created an update to the addon within my own fork that is compatible with Thunderbird 68. I followed up on @nyarlatothep which got part of the addon working by just introducing a manifest.json. In my commit, I made some more changes such that the addon works within the legacy support system.

You can find the relevant commit here; RemcodM/rspamd-spamness@c802cdb3aacd9484e73fe3585e74201a18290f9e

I am not entirely sure that everything works as expected in this commit, but most functionality works as expected. Showing the Rspamd symbols in the header pane works, as well as the spam score column and some other functionality. The buttons to learn ham and learn spam at least appear when enabled, but I am not sure if they work.

It should be noted that the commit introduces 'just enough' changes to let the plugin work within the legacy support layer of Thunderbird. It is not a rewrite and it is probably not very future proof (considering the changes proposed for Thunderbird >70).

**Comment by moisseev** [comment]
@RemcodM  Wow! Thank you.

> I am not entirely sure that everything works as expected in this commit,

I don't have time right now to check everything, but at first sight everything works except centering of the rules dialog window. I guess this part is not finished yet?

> The buttons to learn ham and learn spam at least appear when enabled, but I am not sure if they work.

They don't, but it is fixable:
```diff
diff --git a/chrome/content/scripts/spamness.js b/chrome/content/scripts/spamness.js
index 9f3be6d..89c7a4b 100644
--- a/chrome/content/scripts/spamness.js
+++ b/chrome/content/scripts/spamness.js
@@ -284,7 +284,7 @@ RspamdSpamness.moveMessage = function (folder, isDefault) {
         ? accountPref
         : "extensions.rspamd-spamness.uri.folder" + folder);
 
-    const destination = MailUtils.getFolderForURI(URI);
+    const destination = MailUtils.getExistingFolder(URI);
     if (
         folder === "TrainHam" && (
             isDefault && RspamdSpamness.trainingButtonHamDefaultAction === "copy" ||
```
Would you mind opening a PR?

**Comment by RemcodM** [comment]
> I don't have time right now to check everything, but at first sight everything works except centering of the rules dialog window. I guess this part is not finished yet?

Honestly, I did not notice this bug because GNOME was treating the dialog as a model window and keeping it centred automatically. I thought the existing method was still working, but appearently it is not because the width and height properties are always undefined. Not sure why this doesn't work anymore. Might be a Thunderbird bug.

> They don't, but it is fixable

I applied your patch and made a pull request. Please let me know if you have any remarks.

**Comment by moisseev** [comment]
[Release 1.0.0](https://github.com/moisseev/rspamd-spamness/releases/tag/1.0.0)

@RemcodM Thanks!
