### ISSUE TITLE
Ham/Spam URI for multiple accounts

### ISSUE THREAD

**Issue by Kamik** [moisseev/rspamd-spamness#18]
Please add the possibility to set HAM / SPAM URI per account. Or witch placeholder: 

`"imap://*/INBOX"`
`"imap://*/Junk"`

**Comment by moisseev** [comment]
Actually, this functionality is already implemented, but there are no account specific controls in the `options` dialog yet.

You can set URIs per account in the Config Editor like so:

|Preference Name|Value (folder URI)|
|---|---|
|extensions.rspamd-spamness.account19.uri.folderTrainHam|imap://user%40example.com@imap.example.com/train_ham|
|extensions.rspamd-spamness.account19.uri.folderTrainSpam|imap://user%40example.com@imap.example.com/train_spam|

Replace `account19` in the preference name with a key that identifies the account.
