### ISSUE TITLE
how to configure spam/ham training folders in addon settings? 

### ISSUE THREAD

**Issue by robbosch** [moisseev/rspamd-spamness#24]
It's not clear to me how to set the ham/spam training folders.
I created folders in the IMAP tree of my mail account. Question is, how is the 'syntax' of the folders in the addon settings?
![ksnip_20210315-183255](https://user-images.githubusercontent.com/4028497/111200225-cbd75000-85c1-11eb-9b6e-0f9ae8fd4286.png)

I set them wrong, because the folder settings I put in don't work. I get the message: 'Destination folder location is not set'.
Any pointer?

**Comment by moisseev** [comment]
You need to select destination account in the drop-down box.

**Comment by robbosch** [comment]
Thanks for the quick response.
I have multiple imap accounts configured in Thunderbird. The imap account that has rspamd active on the server is one of them. I have set the destination account by using the 'per account folder settings'
The 'syntax' of the destination folder is unclear to me.

**Comment by gabrix73** [comment]
Syntax is not clear for me too ..

**Comment by moisseev** [comment]
It is just a `folder name`. For nested sub-folder structure it is folder names separated with a forward slash (`/`).
Leading and trailing slashes are optional.

Examples:
```
folder
/folder/
/folder
folder/
folder/folder/folder
/folder/folder/folder
/folder/folder/folder/
folder/folder/folder/
```
