### ISSUE TITLE
Training Buttons do not work in Thunderbird 90+

### ISSUE THREAD

**Issue by alexanderhaensch** [moisseev/rspamd-spamness#26]
The Training HAM and SPAM buttons do not operate in Thunderbird 90+

I tested with IMAP accounts and Local Folders and iterated different folders and subfolders but no change.

From the user perspective clicking the button does not do anything.
I found in the error console:

```
<unavailable> libBackground.js:161:13
    error moz-extension://067a7b4d-2c0b-4fa6-a5c2-2cee80da6179/scripts/libBackground.js:161
    moveMessage moz-extension://067a7b4d-2c0b-4fa6-a5c2-2cee80da6179/scripts/background.js:79
```

interestingly, clicking the button twice does not create a new error in the debug console. Looks like line 80 (Unexspected error) is not hit...

**Comment by moisseev** [comment]
https://github.com/moisseev/rspamd-spamness/commit/923f905f5f93af8ca45ae1e1025c78e126d10ae6 should fix the issue.
The next release is waiting for review, I hope it will be approved soon.

**Comment by alexanderhaensch** [comment]
It works now, thanks
