### ISSUE TITLE
[Bug] [TB102] Spam Score column always reset position in INBOX

### ISSUE THREAD

**Issue by realizelol** [moisseev/rspamd-spamness#28]
If you put "Spam Score" in the last column position und restart TB102 it always resets the position back to the first column.
It doesn't matter if you explicitly "set this columnsettings to all folders"\*. *It will always reset the position.*
(\* Sorry I don't have the exact english meaning of it.)

This issue only appears in INBOX. All other IMAP folders are working correctly.

<br>

best regards
realizelol

**Comment by realizelol** [comment]
Maybe that's easier to understand with some pictures:

If I open Thunderbird it looks like this:
![TBopen](https://user-images.githubusercontent.com/23048339/192093087-61a15ee3-9449-4f69-9c1f-9a0a30350213.png)

If I move it to my column (the last one on the right):
![TBScoreOnTheRight](https://user-images.githubusercontent.com/23048339/192093117-0e627629-c549-431c-ac0e-abf88587a740.png)

The next time I will open it, it looks like this again:
![TBopen](https://user-images.githubusercontent.com/23048339/192093087-61a15ee3-9449-4f69-9c1f-9a0a30350213.png)

If I move into another folder and go back to inbox it's gone:
![TBgone](https://user-images.githubusercontent.com/23048339/192093173-621aace6-e7bc-49c9-9c93-838416f69839.png)

Thank you in advance for your cooperation.

<br>

best regards
realizelol

**Comment by moisseev** [comment]
Thank you for explanation. Actually, I understood the issue, but it is not obvious to me what changes in Thunderbird cause it and right now I don't have enough time for research.

**Comment by schwupp** [comment]
Same issue here. For me it doesn't matter in which column you drag the score, it always reset to first position after restart. Tried on multiple machines. I'm using this plugin for a long time and arranged myself with this bug, so i cannot remember when this has begun. At the moment i'm using:
- TB 102.10.1 (Ubuntu snap)
- Plugin Version 2.0.0a13

Alternative Plugin from [friedPotat0](https://github.com/friedPotat0/Spam-Scores) does work as expected in same scenario, but i like the look and feel from this plugin here ;-)

@moisseev I understood that you're short on time, but if you need someone testing or getting some logs, feel free to ask.

**Comment by moisseev** [comment]
@schwupp , @realizelol Would you test the fix, please?

**Comment by realizelol** [comment]
I can confirm, it's working now. Thank you very much. I will let this issue open so @schwupp can test it too.

Just rename it from `.zip` to `.xpi`:
[rspamd-spamness_2.0.0a14.zip](https://github.com/moisseev/rspamd-spamness/files/11675983/rspamd-spamness_2.0.0a14.zip)

**Comment by schwupp** [comment]
Tested v2.0.0a14 with Windows and Ubuntu TB: It's working again as expected now. Thanks for the fix!
