### ISSUE TITLE
Spam Score not shown when using exim $spam_report

### ISSUE THREAD

**Issue by daugustin** [moisseev/rspamd-spamness#3]
When using this plugin without rmilter, but with exim, the output of the spam report looks slightly different.

```
X-Spam-Score: 6.3 (++++++)
X-Spam-Report: Action: add header
 Symbol: X_PHP_EVAL(4.00)
 Symbol: ONCE_RECEIVED(0.10)
 Symbol: MIME_GOOD(-0.10)
 Symbol: HFILTER_HELO_NORES_A_OR_MX(0.30)
 Symbol: AUTH_NA(1.00)
 Symbol: HFILTER_HELO_IP_A(1.00)
 Message-ID: someid@somespamdomain.com
X-Spam-Flag: YES
```

Even when setting the header flag to "x-spam-report" and rebuilding the index the plugin doesnt seem to catch the header.

Could you add support for this header style?

**Comment by moisseev** [comment]
Setting the header flag to `x-spam-report` won't work for Exim headers for now.
I'm planning to add Exim headers support soon, it seems not complicated.

**Comment by moisseev** [comment]
Would you test that please? https://github.com/moisseev/rspamd-spamness/releases/tag/0.8.0a

You should leave default `x-spamd-result` header setting for Rmilter header, Exim headers are hardcoded for now. The add-on should display headers for messages filtered with Rspamd using any of that integration methods.
You will need to re-index folders to display score  in the column for already received messages.

**Comment by daugustin** [comment]
Yes, with the default header setting it works. Confusingly, when setting this to x-spam-report it does not.

Thank you.
