### ISSUE TITLE
Please add an option to select default action (copy or move) to TrainHam/TrainSpam

### ISSUE THREAD

**Issue by mkosmach** [moisseev/rspamd-spamness#6]

**Comment by moisseev** [comment]
Another option is to create another set of buttons with different look (color, label, icons, etc). Configurable buttons seems more elegant solution, but IMHO a little confusing if the same buttons can have different default actions. What do you think?

**Comment by mkosmach** [comment]
Another set of buttons is ok for me too.
I think that would be one-time option. I.e. user adds one of two sets of buttons to panel or select default action only during the initial setup.

**Comment by sander85** [comment]
Hi!

The default action in Thunderbird 52 doesn't seem to work. Also when I click on the end of the training button to see options then I see two empty options, first seems to move the message and the other will copy it but there is no text so you have to guess. Default action is also not considered when used from context menu.

I'm running this Thunderbird on Linux but this shouldn't matter much in this case.

Regards,
Sander

**Comment by moisseev** [comment]
@sander85 , thank you for the report. I've reproduced both issues. They are not related to Thunderbird version or OS. For some reason after adding buttons their dropboxes and context menu do not work properly until Thunderbird is restarted.

**Comment by moisseev** [comment]
@sander85 , your issues should be fixed.
