### ISSUE TITLE
Spam Scores have stopped showing (Thunderbird 51 x86 & Rspamd-spamness 0.8.4)

### ISSUE THREAD

**Issue by Optimaximal** [moisseev/rspamd-spamness#9]
As topic - I use Thunderbird to check on an IMAP folder every so often that collects email from a few mailboxes and I use this for SPAM/HAM training.

The server is running rspamd 1.6.5-4~xenial and i'm not sure if they've intentionally removed the `X-Spamd-Result` tag, but the headers now have `X-Spam-Status`, `X-Spam-Score` and `X-Spam-Report`.

Example - 
X-Spam-Status: No
X-Spam-Score: -1.2 (-)
X-Spam-Report: Action: no action
 Symbol: MIME_GOOD(-0.10)
 Symbol: RCPT_COUNT_ONE(0.00)
 Symbol: TO_MATCH_ENVRCPT_ALL(0.00)
 Symbol: SUBJ_EXCESS_QP(1.20)
 Symbol: MIME_HTML_ONLY(0.20)
 Symbol: RWL_MAILSPIKE_VERYGOOD(0.00)
 Symbol: RCVD_NO_TLS_LAST(0.00)
 Symbol: DMARC_POLICY_ALLOW(-0.25)
 Symbol: MID_RHS_MATCH_FROM(0.00)
 Symbol: REPLYTO_DOM_NEQ_FROM_DOM(0.00)
 Symbol: PREVIOUSLY_DELIVERED(0.00)
 Symbol: ARC_NA(0.00)
 Symbol: FROM_NEQ_ENVFROM(0.00)
 Symbol: HTML_SHORT_LINK_IMG_2(1.00)
 Symbol: R_DKIM_ALLOW(-0.20)
 Symbol: RCVD_IN_DNSWL_NONE(0.00)
 Symbol: BAYES_HAM(-3.00)
 Symbol: HAS_REPLYTO(0.00)
 Symbol: MIME_MA_MISSING_TEXT(2.00)
 Symbol: TO_DN_EQ_ADDR_ALL(0.00)
 Symbol: IP_SCORE(-3.17)
 Symbol: URI_COUNT_ODD(1.00)
 Symbol: RCVD_COUNT_TWO(0.00)
 Symbol: FORGED_SENDER(0.30)
 Symbol: FROM_HAS_DN(0.00)
 Symbol: ASN(0.00)
 Symbol: R_SPF_ALLOW(-0.20)

**Comment by moisseev** [comment]
The headers in the example look like Exim's headers. It's fine. They are supported as well.
I've tried to create a message with the headers from your example and score and symbols are showing (checked with TB 59.0a1). I think the issue is not related to the headers.
Though it might be a problem with headers folding or something. Can you attach unmodified headers to the issue as a file?

**Comment by Optimaximal** [comment]
Sorry for the delay in the reply...

Here's another random example...

Return-Path: <bounce@newscastmail.co.uk>
Delivered-To: #######@###########.##.##
Received: from ####.######.##.##
	by #########.#######.##### (Dovecot) with LMTP id P6RmMkTpZVq6BgAAMCMpmQ
	for <#######@###########.##.##>; Mon, 22 Jan 2018 13:38:12 +0000
Received: from vps2.newscastmail.co.uk ([213.246.100.170])
	by ####.######.##.## with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
	(Exim 4.86_2)
	(envelope-from <bounce@newscastmail.co.uk>)
	id 1edcIe-0000Ri-DZ
	for #######@###########.##.##; Mon, 22 Jan 2018 13:38:12 +0000
Received: by vps2.newscastmail.co.uk (Postfix, from userid 10000)
	id F28FA2158F; Mon, 22 Jan 2018 13:34:22 +0000 (GMT)
To: #######@###########.##.##
Subject: FW: Email Campaign Enquiry
X-PHP-Originating-Script: 10000:email.php
Message-ID: <4b41209437510b5cb45b67e40c4c2343@www.newscastmail.co.uk>
Date: Mon, 22 Jan 2018 13:32:02 +0000
From: "Michael Lindsay" <sales@newscastmail.co.uk>
Reply-To: sales@newscastmail.co.uk
MIME-Version: 1.0
X-Mailer-LID: 202
List-Unsubscribe: <http://www.newscastmail.co.uk/iem/unsubscribe.php?M=2289334&C=db55245777d08c4b0051290863ca1114&L=202&N=298>
X-Mailer-RecptId: 2289334
X-Mailer-SID: 298
X-Mailer-Sent-By: 1
Content-Type: multipart/alternative; charset="UTF-8"; boundary="b1_53e15bc89fab7cfb4d1ab66c74d2facb"
Content-Transfer-Encoding: 8bit
X-Spam-Status: No
X-Spam-Score: 2.9 (++)
X-Spam-Report: Action: no action
 Symbol: MIME_GOOD(-0.10)
 Symbol: RCPT_COUNT_ONE(0.00)
 Symbol: HAS_PHPMAILER_SIG(0.00)
 Symbol: RCVD_NO_TLS_LAST(0.00)
 Symbol: TO_MATCH_ENVRCPT_ALL(0.00)
 Symbol: HAS_INTERSPIRE_SIG(1.00)
 Symbol: HAS_X_POS(0.00)
 Symbol: ARC_NA(0.00)
 Symbol: FROM_NEQ_ENVFROM(0.00)
 Symbol: R_SPF_ALLOW(-0.20)
 Symbol: DMARC_NA(0.00)
 Symbol: R_DKIM_NA(0.00)
 Symbol: HAS_REPLYTO(0.00)
 Symbol: IP_SCORE(-2.43)
 Symbol: RCVD_COUNT_TWO(0.00)
 Symbol: FORGED_SENDER(0.30)
 Symbol: PHISHING(3.86)
 Symbol: MID_RHS_WWW(0.50)
 Symbol: TO_DN_NONE(0.00)
 Symbol: FROM_HAS_DN(0.00)
 Symbol: ASN(0.00)
 Symbol: REPLYTO_ADDR_EQ_FROM(0.00)
 Message: (SPF): spf allow
 Message-ID: 4b41209437510b5cb45b67e40c4c2343@www.newscastmail.co.uk

Here's the mail in Thunderbird - plugin column on the right-hand side.

![screenshot 2018-02-01 14 54 04](https://user-images.githubusercontent.com/4669242/35685021-698e0d18-0760-11e8-9043-25a3119d58a0.png)

**Comment by moisseev** [comment]
I've saved your sample to a file and imported it in Thunderbird. Everything looks fine.
![2018-02-01 18_14_18-exim - daily](https://user-images.githubusercontent.com/2275981/35686138-a10096be-077c-11e8-8937-1e19869aeecf.png)
I think your problem is not related to the headers.

Please try to re-index the folder in Thunderbird.
To re-index the folder, select it and choose `Properties...` from the context or Edit menu, then click the `Repair Folder` button.

**Comment by Optimaximal** [comment]
I've done a Repair on the imap folders in question - this resets everything, disabling the rspamd-spamness column.

Enabling it again returns blanks.
![screenshot 2018-02-02 10 25 30](https://user-images.githubusercontent.com/4669242/35728430-76bf46fc-0803-11e8-90ed-946a50cdcf79.png)
![screenshot 2018-02-02 10 24 48](https://user-images.githubusercontent.com/4669242/35728432-79d0f7f0-0803-11e8-852e-ba8199bb6d3b.png)
![screenshot 2018-02-02 10 25 16](https://user-images.githubusercontent.com/4669242/35728434-7b91cae2-0803-11e8-930a-2513cef6337b.png)

Ideas?

**Comment by moisseev** [comment]
Are there any messages related to rspamd-spamness in the `Error Console`?
Tools --> Developer Tools --> Error Console
What version of Thunderbird you are using?

**Comment by Optimaximal** [comment]
Nothing :/

Thunderbird is 52.5.2. I'm updating to 52.6 now.

**Comment by Optimaximal** [comment]
Ahh, I turned on full logging and, despite the buttons in the mail messages appearing, clicking one threw this error:

`ReferenceError: RspamdSpamness is not defined` in messenger.xul

![screenshot 2018-02-02 12 20 25](https://user-images.githubusercontent.com/4669242/35732984-7548e8fe-0813-11e8-9c6b-731111aab566.png)

**Comment by Optimaximal** [comment]
Right, completely removing the plugin & reinstalling it seems to have solved it this time - I'm sure I had already done that, but I guess not.

**Comment by moisseev** [comment]
Good to know. Can this issue be closed now?

**Comment by Optimaximal** [comment]
Sorry, yes.

Turns out it was McAfee Endpoint 10.5 taking umbrage at the extension!

`Description: | X ran C:\Program Files (x86)\Mozilla Thunderbird\thunderbird.exe, which tried to access C:\Users\X\AppData\Local\Thunderbird\Profiles\sgzz4s7n.default\cache2\entries\16076494CEF5C32EF14D4B837F9DB94A72602D2F\column.js. The Potentially Unwanted Program named Suspicious Attachment!script was detected and deleted.
-- | --


`
